#!/bin/ksh
set -euax

libs="-L//home/Jack.Woollen/lib  -lbufr_4_64   -lbacio_4 -lip_4 -lg2_4  -lw3nco_4 -ljasper -lpng -lz -lsp_4"

#FC=ifort
#FC_FLAGS=-stand:f08  -fp-model precise -fp-model source -fp-stack-check -g -traceback -check all -warn all -c

#ifort -traceback -g -FR -o $1.x $1.f90 $libs 
ifort  -o $1.x $1.f90 $libs 


